- src/minio.rs
- src/minio/api_notification.rs
In an effort to imitate some of the `minio-go` code organization I moved `listen_bucket_notification` to it's own file at `api_notification.rs`
> Refactor Notification API. Move code to it's own file.

- src/s3/client.rs
- tests/tests.rs
> fix get_presigned_object_url() API to use host header value

- src/s3/args.rs
- src/s3/client.rs
- tests/tests.rs
This change lets the Client struct take ownership of the Provider trait object so that we are remove the lifetime parameter from the Client.
This change simplifies usage of the Client object. Without this it is difficult to pass the Client object to a thread.
> Remove lifetime parameter from client

- .github/workflows/rust.yml
- src/s3/client.rs
- tests/tests.rs
Builder style makes it easier to construct the Client because each setting is done via a separate function thus documenting the purpose the setting.
Ref: https://rust-lang.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder
> Add builder style constructor for Client

- Cargo.toml
- src/s3/args.rs
- src/s3/client.rs
- src/s3/client/listen_bucket_notification.rs
- tests/tests.rs
- Add doc on list_bucket_notification API.
Iteration style is easier to use as the code is more linear. I am not sure callback style is better suited for any particular problem (let me know if this is not right).
> Add streaming support to listen_bucket_notification() API

- Cargo.toml
- examples/file-uploader.rs
- src/lib.rs
- src/s3/args.rs
- src/s3/client.rs
- src/s3/client/listen_bucket_notification.rs
- src/s3/http.rs
- src/s3/types.rs
- tests/start-server.sh
- tests/tests.rs
This PR fixes a deprecated lifetime issue, does some clippy warning fixes, and a update to the file-uploader example to give an error when the file to be uploaded cannot be found
> fix deprecated lifetime; update example file-uploader

- src/s3/error.rs
- src/s3/response/list_objects.rs
- src/s3/utils.rs
For list-object-versions there was a bug that would return delete
markers after all versions of an object. The server response contains
the order of versions and delete markers according to recency and the
list objects client call should preserve this. This is fixed in this
change.
XML parsing was using the `take_child` call, that mutates a vector
removing an element in it. For a response containing N items, using
take_child on item, causes the XML parsing cost to be O(N^2) (so 1
million operations for a 1000 item list) - this change makes the parsing
cost linear.
> Fix list objects xml parsing bug and improve perf.

- Cargo.toml
- examples/file-uploader.rs
- src/s3/args.rs
- src/s3/builders/get_object.rs
- src/s3/builders/object_content.rs
- src/s3/builders/put_object.rs
- src/s3/client.rs
- src/s3/client/get_object.rs
- src/s3/client/put_object.rs
- src/s3/error.rs
- src/s3/http.rs
- src/s3/response.rs
- src/s3/response/get_object.rs
- src/s3/response/put_object.rs
- src/s3/sse.rs
- src/s3/types.rs
- src/s3/utils.rs
- tests/tests.rs
- put_object_content -> streaming object uploads
- put_object_from_file -> upload file
- put_object, create_multipart_uload, abort_multipart_upload,
upload_part, complete_multipart_upload -> S3 APIs for single and
multipart uploads
- get_object -> streaming object downloads
> Add new put and get APIs for objects

- src/s3/client.rs
Fixed the error where the path does not exist when downloading files with paths like 'xxx/xxx/xxx/xxx.xx'.
> Fix download file error

- src/s3/args.rs
- src/s3/builders.rs
- src/s3/builders/remove_objects.rs
- src/s3/client.rs
- src/s3/client/remove_objects.rs
- src/s3/client_core.rs
- src/s3/response.rs
- src/s3/response/remove_objects.rs
- src/s3/types.rs
- tests/tests.rs
> Add builder style remove_object(s) APIs

- Cargo.toml
- examples/put-object.rs
- src/s3/error.rs
- src/s3/http.rs
- src/s3/utils.rs
URL encoding for S3 API requires that we do not encode '/' in addition to the standard characters (`_-~.` and alphanumerics).
Also fixes a bug in error response parsing (bucket name was not parsed correctly).
Also adds another put-object example accepting CLI args.
> fix: missing URL encoding for object names

- src/s3/types.rs
Some events e.g. s3:Replication:OperationCompletedReplication send 'null' value in request_parameters and the deserialization can fail in such cases ('deault' doesn't help here)
Marking this field as optional will ensure that such events can also be deserialized without any error.
> Make request_parameters optional

- src/s3/builders/list_objects.rs
- src/s3/client/list_objects.rs
- src/s3/response.rs
Unexports `list_objects_v1`, `list_objects_v2` and `list_object_versions` and associated request/response types.
These are not necessary as the higher level `list_objects()` can be used instead for equivalent functionality.
> Unexport unnecessary list functions

- src/s3/builders/put_object.rs
- tests/tests.rs
For now `PutObjectContent.content_type` doesn't work, this pr fixes it
> Respect content_type prop

- Cargo.toml
- src/s3/client.rs
The `.ssl_cert_file()` option now can read files with multiple certificate to trust. This is useful when using a single client instance to access many minio servers.
> feat: allow multiple trust certs in cert file

- .github/comprehensive-release.yml
- .github/release.yml
- .github/workflows/label-checker.yaml
- .github/workflows/lint.yml
Added release notes automation. Appreciate that this update only adds that the build checks that labels are used such that the docs team can generate release notes.
> Added release notes automation

- Cargo.toml
- src/s3/builders/put_object.rs
- tests/run-tests-windows.ps1
- tests/tests.rs
Note: depends on https://github.com/minio/minio-rs/pull/114
Refactored one large test into separate tests. It runs 2 twice as fast as a result
> refactored tests into 24 separate tests

- Cargo.toml
- src/s3/client.rs
os_info is too heavy, for the purposes of this library using the consts in std::env are enough
Fixes #107
> Remove os_info dep

- src/s3/client.rs
Client struct is not truly cheap to clone since DashMap clone is not cheap. Wrap it in an Arc to fix this.
> Wrap region headers map in an Arc

- Cargo.toml
- src/s3/signer.rs
- src/s3/utils.rs
- tests/test_upload_download_object.rs
Ring has a faster hash implementation than sha2 crate. After profiling with samply and analysing flamegraph, hash computation call from sha256_hash_sb cpu usage went down to 2.6% from 13% just from this change.
> optimize: use ring hash and hmac implementations

- src/s3/client.rs
Use #[async_recursion] instead of #[async_recursion(?Send)], which make minio::s3::client::Client::copy_object work on tokio::spwan and axum reqwuest handler. If we still need Sync here, may switch to #[async_recursion(Sync)].
#[async_recursion] modifies your function to return a boxed Future with a Send bound.
#[async_recursion(?Send)] modifies your function to return a boxed Future without a Send bound.
#[async_recursion(Sync)] modifies your function to return a boxed Future with a Send and Sync bound.
This is a master branch demo with Send limit, can't compile.
```rust
use minio::s3::{
args::{CopyObjectArgs, CopySource},
creds::StaticProvider,
Client,
};
#[tokio::main]
async fn main() {
tokio::spawn(copy_image(
"bucket_from",
"bucket_to",
"filename".to_owned(),
));
}
pub async fn …
```
> Remove copy_object !Send

- src/s3/builders/copy_object.rs
- src/s3/builders/put_object.rs
- src/s3/builders/remove_objects.rs
- src/s3/client/append_object.rs
- src/s3/client/copy_object.rs
- src/s3/client/put_object.rs
- src/s3/client/set_object_retention.rs
- src/s3/client/set_object_tags.rs
- src/s3/client/stat_object.rs
- src/s3/error.rs
- src/s3/multimap.rs
- src/s3/response/append_object.rs
- src/s3/response/get_bucket_versioning.rs
- src/s3/response/get_object.rs
- src/s3/response/get_object_lock_config.rs
- src/s3/response/list_objects.rs
- src/s3/response/object_prompt.rs
- src/s3/response/put_object.rs
- src/s3/utils.rs
- tests/test_append_object.rs
- tests/test_object_put.rs
- tests/test_put_object.rs
Some minor issues that came up while writing docs
> minor issues

- README.md
Clarify and add additional information about the Rust SDK, in preparation for automated inclusion in the public documentation.
- Minor rework of existing text
- Incorporate documentation from src/lib.rs in the readme
> Update the README with additional information

- common/src/test_context.rs
- examples/common.rs
- examples/object_prompt.rs
- examples/put_object.rs
- src/s3/client.rs
A `Box` is a pointer and an `Arc` is a smart pointer, we can remove one layer of indirection by directly using `Arc`. 
We can also remove the need for our caller to box / arc the input by making the respective functions generic over `Provider`.
> fix: replace Arc<Box<...>> credential-provider with Arc<...>

- src/s3/client/delete_bucket.rs
This PR enhances the delete_and_purge_bucket method by enabling recursive traversal when listing objects, ensuring nested items and versions are deleted.
> bugfix: delete_and_purge_bucket add recursive delete

- common/src/cleanup_guard.rs
- src/s3/builders/copy_object.rs
- src/s3/builders/put_object.rs
- src/s3/client/delete_bucket.rs
- src/s3/multimap.rs
- src/s3/response/list_objects.rs
- src/s3/utils.rs
- tests/test_bucket_create_delete.rs
- tests/test_get_object.rs
- tests/test_list_objects.rs
- tests/test_object_copy.rs
- tests/test_object_delete.rs
- tests/test_upload_download_object.rs
The url_decode function now correctly decodes "a+b%2Bc" into "a b+c" instead of the incorrect "a+b+c".
Every function that uses either url_encode or url_decode now has dedicated tests to ensure correct handling of whitespace.
> Bugfix: whitespace in object name
